#!/bin/sh
tmp=(~/.mozilla/firefox/*.default-release)
sqlite3 ${tmp[0]}/cookies.sqlite \
    "select value from moz_cookies where name='session' and host='.adventofcode.com';" >~/.adventofcode.session
