#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use Data::Dumper;
use List::Util qw(product sum);

@ARGV = shift // "input";

my $sol1 = 0;
my $sol2 = 0;

while (<>) {
    chomp;
    
}

say "Solution 1: $sol1";
say "Solution 2: $sol2";

# vim:ft=perl:sts=4:sw=4:et
