#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]

proc md {x1 y1 x2 y2} {
    + [abs [- $x1 $x2]] [abs [- $y1 $y2]]
}

proc run {} {

    set data [read -nonewline stdin]
    set lines [lmap l [split $data \n] {
        regsub -all {[^-0-9]} $l { } }]

    set sc [list]
    set ka [list]
    set kb [list]

    foreach l $lines {
        lassign $l sx sy bx by
        set r [md $sx $sy $bx $by]
        lappend sc $sx $sy $r
        lappend ka [+ $sy -$sx  $r  1]
        lappend ka [+ $sy -$sx -$r -1]
        lappend kb [+ $sx  $sy  $r  1]
        lappend kb [+ $sx  $sy -$r -1]
    }
    puts $sc
    puts $ka 
    puts $kb


    foreach {x y} {14 11 12 11 2 26} {
        puts "$x $y"
        foreach {sx sy r} $sc {
            set rs [md $x $y $sx $sy]
            puts "  $sx $sy $rs $r"
        }
    }
}
run
