#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]
package require fileutil
package require textutil

proc run {file} {

    set in [open $file r]
    set data [read -nonewline $in]
    
    array set win { A Y B Z C X}
    array set score {X 1 Y 2 Z 3}
    array set same {A X B Y C Z}

    set games [split $data \n]

    set scores [lmap g $games {
            lassign $g them me
            + [* 6 [eq $win($them) $me]] [* 3 [eq $same($them) $me]] $score($me)
        }]

    puts [join $scores \n]

    puts [+ {*}$scores]
}

run [lindex $argv 0]
