#!/usr/bin/perl
# vim:ft=perl

use v5.38;

@ARGV = shift // "input";

my $solution_1 = 0;
my $solution_2 = 0;

my %rules;

while (<>) {
    last unless /^(\d+)\|(\d+)/;
    $rules{$1}{$2} = -1;
}

while (<>) {
    my @sort = sort { $rules{$a}{$b} // 1 } my @list = /\d+/g;
    if   ( "@list" eq "@sort" ) { $solution_1 += $list[ @list / 2 ] }
    else                        { $solution_2 += $sort[ @sort / 2 ] }
}

say "Solution 1: $solution_1";
say "Solution 2: $solution_2";

