#!/usr/bin/env perl

use 5.038;

use strict;
use warnings;

@ARGV = shift // "input";

my $sol1 = 0;
my $sol2 = 0;

for ( split /,/, <> ) {
    my ( $a, $b ) = /(\d+)-(\d+)/;
    for ( $a .. $b ) {
        my $n = $_;
        my $s = sprintf "%d", $n;
        my $l = length $s;
        for ( 2 .. $l ) {
            my $i = $_;
            next if ( $l % $i );
            my $j = $l / $i;
            my @p;
            for my $k ( 0 .. $i - 1 ) {
                push @p, substr( $s, $k * $j, $j );
            }
            my $equal = 1;
            for ( 1 .. $#p ) {
                if ( $p[0] ne $p[$_] ) {
                    $equal = 0;
                    last;
                }
            }

            if ($equal) {
                $sol2 += $n;
                if ( $i == 2 ) {
                    $sol1 += $n;
                }
                last;
            }
        }
    }
}

print "Solution 1: $sol1\n";
print "Solution 2: $sol2\n";

# vim:ft=perl:sts=4:sw=4:et
