#!/usr/bin/perl

use v5.38;
use List::Util qw(sum);
use List::MoreUtils qw(:all);

@ARGV = "input" unless @ARGV;

my $solution_1 = 0;
my $solution_2 = 0;

say "Solution 1: $solution_1";
say "Solution 2: $solution_2";

__END__
# :%! perltidy -pbp -xci
# vim:ft=perl:sts=4:sw=4:et

