#!/usr/bin/perl

use v5.38;
use integer;

@ARGV = shift // "input";

my $solution_1 = 0;
my $solution_2 = 0;

sub results;

sub results ( $part, $f = undef, $s = undef, @rest ) {
    return
          !defined $f ? ()
        : !defined $s ? $f
        : ( results( $part, $f + $s, @rest ),
            results( $part, $f * $s, @rest ),
            $part == 1 ? () : results( $part, $f . $s, @rest ),
        );
}

while (<>) {
    my ( $total, @parts ) = /[0-9]+/g;
    $solution_1 += $total if grep { $_ == $total } results 1, @parts;
    $solution_2 += $total if grep { $_ == $total } results 2, @parts;
}

say "Solution 1: $solution_1";
say "Solution 2: $solution_2";

# vim:ft=perl:sts=4:sw=4:et
