#!/usr/bin/perl

use v5.38;
use bigint;

@ARGV = shift // "input";

my $solution_1 = 0;
my $solution_2 = 0;

my $types = 3;

LOOP:
while (<>) {
    my ( $result, $rest ) = split /:\s*/, $_, 2;
    my @factors = split ' ', $rest;
    my $n       = @factors - 1;
    for my $ops ( 0 .. ( $types**$n ) - 1 ) {
        my ( $x, @stack ) = @factors;
        my $op = $ops;
        my $t3 = 0;
        while ( my $y = shift @stack ) {
            my $r = $op % $types;
            $op /= $types;
            if ( $r == 0 ) {
                $x += $y;
            }
            elsif ( $r == 1 ) {
                $x *= $y;
            }
            else {
                $t3 = 1;
                $x .= $y;
            }
        }
        if ( $x == $result ) {
            if ( !$t3 ) {
                $solution_1 += $result;
                $solution_2 += $result;
            }
            if ($t3) {
                $solution_2 += $result;
            }
            next LOOP;
        }
    }
}

say "Solution 1: $solution_1";
say "Solution 2: $solution_2";

# vim:ft=perl:sts=4:sw=4:et
