#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]
package require fileutil
package require textutil
namespace import ::textutil::split*

proc run {} {

    set data [read -nonewline stdin]
    set data [string map {; " " , " " = " "} $data]

    foreach line [split $data \n] {
        set valve [lindex $line 1]
        set rate [lindex $line 5]
        set valves [lrange $line 10 end]
        puts "$valve $rate $valves"
    }

}

run
