#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path ::tcl::mathop

set t { 28 20 25 13 21 21 13 22 9 3 6 2}

set s 0

foreach {a b } $t {
    set p [* $a $b]
    puts "$a $b $p"
    incr s $p
}
puts ""
puts $s
