#!/usr/bin/env tclsh
namespace path [list ::tcl::mathop ::tcl::mathfunc]
package require fileutil
package require textutil

proc a {file} {

    set in [open $file r]
    set data [read -nonewline $in]

    set pars [textutil::splitx $data \n\s*\n]

    set lines [lmap p $pars {list {*}$p}]

    puts [join $lines \n]

    set max 0

    foreach l $lines {
        set max [max $max [+ {*}$l]]
    }
    puts $max
}

a [lindex $argv 0]

