#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use Data::Dump qw(dump);
use List::Util qw( product sum);

@ARGV = shift // "input";

my $sol1 = 0;
my $sol2 = 0;

my ( @input, @data, @trans );

while ( my $line = <> ) {
    chomp $line;
    push @input, $line;
}

for my $i ( 0 .. $#input ) {
    push @data, [ split " ", $input[$i] ];
}

for my $i ( 0 .. $#data ) {
    for my $j ( 0 .. $#{ $data[0] } ) {
        $trans[$j][$i] = $data[$i][$j];
    }
}

for (@trans) {
    my @line = @$_;
    my $op   = pop @line;
    if ( $op eq '+' ) { $sol1 += sum @line; }
    if ( $op eq '*' ) { $sol1 += product @line; }
}

my ( @data2, @trans2 );

for my $i ( 0 .. $#input ) {
    push @data2, [ split "", $input[$i] ];
}

my @ops = grep { !/ / } @{ pop @data2 };

for my $i ( 0 .. $#data2 ) {
    for my $j ( 0 .. $#{ $data2[0] } ) {
        $trans2[$j][$i] = $data2[$i][$j];
    }
}
push @trans2, [" "];

my @nums;
for (@trans2) {
    my $line = join "", @$_;
    if ( $line =~ /^\s+$/ ) {
        my $op = shift @ops;
        if ( $op eq '+' ) { $sol2 += sum @nums; }
        if ( $op eq '*' ) { $sol2 += product @nums; }
        @nums = ();
    }
    else {
        push @nums, $line;
    }
}

say "Solution 1: $sol1";
say "Solution 2: $sol2";

# vim:ft=perl:sts=4:sw=4:et
