#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]

set data [read -nonewline stdin]
set lines [split $data \n]

foreach line $lines {
    lassign [split $line :] label cards
    set ticket [lindex $label 1]
    lassign [split $cards |] win have

    set score 0
    foreach card $have {
        if {$card in $win} {
            if {$score} {
                set score [* $score 2]
            } else {
                set score 1
            }
        }
    }
    incr sum $score
}
puts $sum
