#!/usr/bin/env perl
use 5.038;
use strict;
use warnings;

@ARGV = shift // "input";

my $sol1 = 0;
my $sol2 = 0;

while (<>) {
    chomp;
    my @a = split //, $_;
    $sol1 += joltage( \@a, 2 );
    $sol2 += joltage( \@a, 12 );
}

print "Solution 1: $sol1\n";
print "Solution 2: $sol2\n";

sub joltage {
    my ( $p, $bat ) = @_;
    my @a = @$p;

    my $s = "";
    my $i = 0;
    for my $b ( 1 .. $bat ) {
        my $d = $a[$i];
        for my $j ( ( $i + 1 ) .. ( $#a - $bat + $b ) ) {
            my $e = $a[$j];
            if ( $e > $d ) {
                $d = $e;
                $i = $j;
            }
        }
        $s .= $d;
        $i++;
    }
    $s;
}

# vim:ft=perl:sts=4:sw=4:et
