#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]
package require textutil
namespace import ::textutil::split*

proc run {} {
    set data [read -nonewline stdin]
    set pieces [splitx $data \n\s*\n]
    set rest [lassign $pieces first]
    lassign [split $first :] junk seeds
    set tables [lmap l $rest { lrange [split $l \n] 1 end }]

    set res 0
    foreach {st num} $seeds {
        for {set seed $st} {$seed < [+ $st $num]} {incr seed} {
            set src $seed
            foreach table $tables {
                foreach row $table {
                    lassign $row d s i
                    if {[<= $s $src [+ $s $i]]} {
                        set src [+ $d [- $src $s]]
                        break
                    }
                }
            }
            if {!$res} {
                set res $src
            } else {
                set res [min $res $src]
            }
        }
    }
    puts $res
}
run
