#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]
set data [read -nonewline stdin]
lassign [lmap l [split $data \n] {lindex [split $l :] end}] times dists

foreach T $times R $dists {
    set F [sqrt [- [* $T $T] [* 4 $R]]]
    set p1 [/ [- $T $F] 2.0]
    set p2 [/ [+ $T $F] 2.0]
    set d [int [- [ceil $p2] [floor $p1] 1]]
    lappend res $d
}
puts [* {*}$res]
