#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]

proc run {} {

    set data [read -nonewline stdin]
    lassign [split $data \n] l1 l2
    lassign [split $l1 :] junk times
    lassign [split $l2 :] junk dists

    set T [string map {{ } {}} $times]
    set R [string map {{ } {}} $dists]

    set F [sqrt [- [* $T $T] [* 4 $R]]]
    set p1 [int [/ [- $T $F] 2.0]]
    set d1 [- [* $p1 $T] [* $p1 $p1]]
    if {[<= $d1 $R]} {incr p1}
    set p2 [int [/ [+ $T $F] 2.0]]
    set d2 [- [* $p2 $T] [* $p2 $p2]]
    if {[<= $d2 $R]} {incr p2 -1}
    set d [- $p2 $p1 -1]
    puts $d
}
run
