#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 
    namespace path [list ::tcl::mathop ::tcl::mathfunc]
    set data [read -nonewline stdin]
    lassign [split $data \n] l1 l2
    lassign [split $l1 :] junk times
    lassign [split $l2 :] junk dists
    set T [string map {{ } {}} $times]
    set R [string map {{ } {}} $dists]
    set F [sqrt [- [* $T $T] [* 4 $R]]]
    set p1 [/ [- $T $F] 2.0]
    set p2 [/ [+ $T $F] 2.0]
    puts [int [- [ceil $p2] [floor $p1] 1]]
