#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

    set data [read -nonewline stdin]
    lassign [split $data \n] l1 l2
    lassign [split $l1 :] junk times
    lassign [split $l2 :] junk dists
    set T [string map {{ } {}} $times]
    set R [string map {{ } {}} $dists]
    set F [expr {sqrt($T*$T-4*$R)}]
    set p1 [expr {($T-$F)/2.0}]
    set p2 [expr {($T+$F)/2.0}]
    puts [expr {ceil($p2)-floor($p1)-1}]
