#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 
    namespace path [list ::tcl::mathop ::tcl::mathfunc]
    set data [read -nonewline stdin]
    lassign [lmap l [split $data \n] {
        string map {{ } {}} [lindex [split $l :] end]}] T R
    set F [sqrt [- [* $T $T] [* 4 $R]]]
    set p1 [/ [- $T $F] 2.0]
    set p2 [/ [+ $T $F] 2.0]
    puts [int [- [ceil $p2] [floor $p1] 1]]
