#!/usr/bin/env perl

use strict;
use warnings;

@ARGV = shift // "input";

my $sol1 = 0;
my $sol2 = 0;

my @grid;

while (<>) {
    chomp;
    push @grid, [split //];
    
}

my $m = $#grid;
my $n = $#{$grid[0]};

for my $i (0 .. $m) {
    for my $j (0 .. $n) {
        my $c = $grid[$i][$j];
        my $s = 0;
        next if $c ne '@';
        for my $di (-1, 0, 1) {
            for my $dj (-1, 0, 1) {
                next if $di == 0 && $dj == 0;
                ++$s if check($i, $j, $di, $dj);
            }
        }
        ++$sol1 if $s < 4;
    }
}

print "Solution 1: $sol1\n";
print "Solution 2: $sol2\n";

sub check {
    my ($i, $j, $di, $dj) = @_;
    my $is = $i + $di;
    return 0 if $is < 0 || $is > $m;
    my $js = $j +$dj;
    return 0 if $js < 0 || $js > $n;
    my $c = $grid[$is][$js];
    return 1 if $c eq '@';
}




# vim:ft=perl:sts=4:sw=4:et
