#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]

set input [read -nonewline stdin]

set dirs {N {0 -1} E {1 0} S {0 1} W {-1 0}}
set nbs { N {| 7 F} S {| L J} W {- F L} E {- J 7}}
set bend {| {N S} - {W E} L {E N}
          J {W N} 7 {W S} F {E S}
          S {W E N S}}

proc run {} {
    global input res dirs nbs bend
    set res 0

    set grid [lmap l [split $input \n] {split $l {}}]
    set m [llength $grid]
    set n [llength [lindex $grid 0]]

    set conc [concat {*}$grid]
    set s [lsearch $conc S]
    set x [% $s $n]
    set y [/ $s $m]
    dict incr done "$x $y"
    set todo [list $x $y 0]

    while {[llength $todo]} {
        set todo [lassign $todo x y d]
        set res [max $res $d]
        set p [lindex $grid $y $x]
        set bends [dict get $bend $p]
        incr d
        foreach dir {N S E W} {
            if {!($dir in $bends)} continue
            lassign [dict get $dirs $dir] dx dy
            set nx [+ $x $dx]
            set ny [+ $y $dy]
            if {$nx < 0 || $nx == $n || $ny < 0 || $ny == $m} continue
            if {[dict exists $done "$nx $ny"]} continue
            set q [lindex $grid $ny $nx]
            set l [dict get $nbs $dir]
            if {$q in $l} {
                lappend todo $nx $ny $d
                dict incr done "$nx $ny"
            }
        }
    }

    puts $res

    set ngrid [lrepeat $m [lrepeat $n .]]
    foreach k [dict keys $done] {
        lassign $k x y
        lset ngrid $y $x [lindex $grid $y $x]
    }

    foreach l $ngrid {
        puts [join $l {}]
    }

    set res 0
    for {set y 0} {$y < $m} {incr y} {
        set in false
        for {set x 0} {$x < $n} {incr x}  {
            set b [lindex $ngrid $y $x]
            set p [lindex $ngrid $y [- $x 1]]
            if {$b eq "."} {
                if {$in} {
                    incr res
                    lset ngrid $y $x I
                }
                continue
            } 
            set bends [dict get $bend $b]
            if {E in $bends} {
                set l [dict get $nbs W]
                if {$p in $l} {
                    if {"$p$b" eq "L7" || "$p$b" eq "FJ"} {
                        set in [! $in]
                    } else {
                        set in true
                    }
                }
            }
        }
    }

    foreach l $ngrid {
        puts [join $l {}]
    }


}

puts [time run]
puts $res
