#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]

proc run {} {
    set data [read -nonewline stdin]

    set sum 0
    foreach l [split $data \n] {
        set d [regexp -all -inline {\d} $l]
        set d1 [lindex $d 0]
        set d2 [lindex $d end]
        set p [+ $d2 [* 10 $d1]]
        incr sum $p
    }
    puts $sum
}
run
