#!/usr/bin/perl

use v5.38;
use feature qw(multidimensional);

@ARGV = shift // "input";

my $solution_1 = 0;
my $solution_2 = 0;

$/ = '';
my $grid  = [ map { [/./g] } split /\n/, <> ];
my @moves = <> =~ /./g;

#say "@$_" for @$grid;
#say "@moves";

say "Solution 1: $solution_1";
say "Solution 2: $solution_2";

# vim:ft=perl:sts=4:sw=4:et
