#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]
package require struct::set

proc run {file} {
    set in [open $file r]
    set data [read -nonewline $in]
    set lines [split $data \n]
    set packs [lmap l $lines { split $l {} }]
    set items [list]
    foreach {a b c} $packs {
        lappend items [lindex [struct::set intersect $a $b $c] 0]
    }
    set items [lmap i $items {
        set val [scan $i %c]
        if {$val >= 96} {
            - $val 96
        } else {
            - $val 38
        }
    }]
    puts [+ {*}$items]
}

run [lindex $argv 0]
