#!/usr/bin/env perl
use 5.038;
use strict;
use warnings;

@ARGV = shift // "input";

my $sol1 = 0;
my $sol2 = 0;

while (<>) {
    chomp;
    my @a  = split //, $_;
    my $li = 0;
    my $ld = $a[$li];
    for my $i ( 1 .. $#a - 1 ) {
        my $d = $a[$i];
        if ( $d > $ld ) {
            $ld = $d;
            $li = $i;
        }
    }
    my $ri = $li + 1;
    my $rd = $a[$ri];
    for my $i ( $ri + 1 .. $#a ) {
        my $d = $a[$i];
        if ( $d > $rd ) {
            $rd = $d;
            $ri = $i;
        }
    }
    $sol1 += 10 * $ld + $rd;

}

print "Solution 1: $sol1\n";
print "Solution 2: $sol2\n";

# vim:ft=perl:sts=4:sw=4:et
