#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]

proc run {} {

    set data [read -nonewline stdin]
    set lines [lmap l [split $data \n] {
        set n [regsub -all {[^\d]} $l " "]
        list {*}$n}]
                
    puts [join $lines \n]


}

run
