#!/usr/bin/env tclsh
# vim:sts=4:sw=4:tw=80:et:ft=tcl 

namespace path [list ::tcl::mathop ::tcl::mathfunc]
package require fileutil
package require textutil
namespace import ::textutil::split*

proc run {} {

    set data [read -nonewline stdin]
    set cubes [lmap l [split $data \n] {split $l ,}]
    set faces [* 6 [llength $cubes]]

    foreach a $cubes {
        foreach b $cubes {
            foreach {x1 y1 z1} $a {x2 y2 z2} $b {
                set sum [+ [abs [- $x2 $x1]] [abs [- $y2 $y1]] [abs [- $z2 $z1]]] 
                if {$sum == 1} {
                    incr faces -1
                }
            }
        }
    }
    puts $faces
}

run
