#!/usr/bin/perl

use v5.38;
use feature qw(multidimensional);

@ARGV = shift // "input";

my $solution_1 = 0;
my $solution_2 = 0;

my $dial = 50;

while (<>) {
    chomp;
    my ($d, $t) = ($_ =~ /(\S)(\d+)/);
    $t = -$t if ($d eq 'L');
    $dial += $t;
    $dial += 100 if ($dial < 0);
    $dial -= 100 if ($dial > 99);
    print $dial, "\n";
    $solution_1++ if ($dial == 0);


}









say "Solution 1: $solution_1";
say "Solution 2: $solution_2";

# vim:ft=perl:sts=4:sw=4:et
