#!/usr/bin/env perl

use strict;
use warnings;

@ARGV = shift // "input";

my $sol1 = 0;
my $sol2 = 0;
my $dial = 50;

while (<>) {
    chomp;
    my ( $d, $t ) = (/(\S)(\d+)/);
    for ( 1 .. $t ) {
        if ( $d eq 'L' ) {
            $dial = ( $dial - 1 + 100 ) % 100;
        }
        else {
            $dial = ( $dial + 1 ) % 100;
        }
        $sol2++ if ( $dial == 0 );
    }
    $sol1++ if ( $dial == 0 );
}

print "Solution 1: $sol1\n";
print "Solution 2: $sol2\n";

# vim:ft=perl:sts=4:sw=4:et
