#!/usr/bin/env perl
# vim: ft=perl

use strict;
use warnings;
use List::Util qw(all sum);
use List::MoreUtils qw(slide);

my $part = 1;
my $sum = 0;

while (<>) {
    my @values = m/-?\d+/g;
    @values = reverse @values if $part == 2;
    while (1) {
        $sum += $values[-1];
        last if all { $_ == 0 } @values;
        @values = slide { $b - $a } @values;
    }
}
print "Sum: $sum\n";


