#!/usr/bin/env perl

use strict;
use warnings;

@ARGV = shift // "input";

my $sol1 = 0;
my $sol2 = 0;

while (<>) {
    chomp;
    
}

print "Solution 1: $sol1\n";
print "Solution 2: $sol2\n";

# vim:ft=perl:sts=4:sw=4:et
